site_name: Acoustique @ UJM (L3 Musico)
site_description: ECIU Micro-Module on Embedded Real-Time Audio
nav:
    - Cours:
        - ' 1. Le son : production, propagation et réception ' : lectures/propagation-reception.md
        - ' 2. Les paramètres du son ' : lectures/parametres-du-son.md
        - ' 3. Représenter, classer et analyser les sons ' : lectures/representer-analyser.md
        - ' 4. Le son numérique ' : lectures/son-numerique.md
        - ' 5. Psychoacoustique : du signal à la perception ' : lectures/psychoacoustique.md
        - ' 6. Acoustique instrumentale ' : lectures/acoustique-instrumentale.md
        - ' 7. La voix chantée ' : lectures/voix-chantee.md
        - ' 8. Intervalles, gammes et tempéraments ' : lectures/echelles-temperaments.md
        - ' 9. Acoustique des salles ' : lectures/acoustique-des-salles.md
    - Labs:
        - ' 1. Les différents types de sons ' : labs/classification.md
        - ' 2. Les paramètres du son ' : labs/parametres.md
        - ' 3. Le son numérique ' : labs/numerique.md
        - ' 4. Acoustique instrumentale, architecturale et vocale ' : labs/instru.md
    - Code: "https://github.com/inria-emeraude/son"
    
theme: 
  name: yeti
  navigation_depth: 3

site_dir: ../docs
site_url: https://inria-emeraude.github.io/ujm-acoustique/

extra:
    social:
        - type: github
          link: https://inria-emeraude.github.io/ujm-acoustique/
        - type: home
          link: https://inria-emeraude.github.io/ujm-acoustique/
        - type: envelope
          link: mailto:romain.michon@univ-st-etienne.fr

plugins:
  - search

extra_css: [extra.css]

extra:
  search:
    language: fr

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - markdown_include.include:
        base_path: './docs'
